- Development:
    - Demo App:
        href: https://home.brettswift.com/demo
        description: Sample Hello World app routed by NGINX
        icon: kubernetes.png
    - ArgoCD:
        href: https://home.brettswift.com/argocd
        description: GitOps deployment platform
        icon: argocd.png
        widget:
            type: argocd
            url: http://argocd-server.argocd.svc.cluster.local/argocd
            key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJob21lcGFnZTphcGlLZXkiLCJuYmYiOjE3NjQ1NjU3OTIsImlhdCI6MTc2NDU2NTc5MiwianRpIjoiMWUwNDA3MjktYjYzOS00OGVkLTg4YmEtYTc2YTdhOTVjOTcwIn0.McBxRrYT4rth1CDKi-XqcUXIhW_DsS9kf83jHzxTUwY
- Media:
    - Jellyfin:
        href: https://home.brettswift.com/jellyfin
        description: Media server
        icon: jellyfin.png
    - Jellyseerr:
        href: https://jellyseerr.home.brettswift.com
        description: Media requests
        icon: jellyseerr.png
    - Sonarr:
        href: https://home.brettswift.com/sonarr
        description: Series management
        icon: sonarr.png
    - Radarr:
        href: https://home.brettswift.com/radarr
        description: Movies management
        icon: radarr.png
    - Lidarr:
        href: https://home.brettswift.com/lidarr
        description: Music management
        icon: lidarr.png
    - Bazarr:
        href: https://home.brettswift.com/bazarr
        description: Subtitles management
        icon: bazarr.png
    - Prowlarr:
        href: https://home.brettswift.com/prowlarr
        description: Indexers management
        icon: prowlarr.png
- Download:
    - qBittorrent:
        href: https://qbittorrent.home.brettswift.com
        description: BitTorrent client
        icon: qbittorrent.png
    - Sabnzbd:
        href: https://home.brettswift.com/sabnzbd
        description: Usenet client
        icon: sabnzbd.png
    - Flaresolverr:
        href: https://home.brettswift.com/flaresolverr
        description: CAPTCHA solver
        icon: flaresolverr.png
- System:
    - Prometheus:
        href: https://home.brettswift.com/prometheus
        description: Metrics collection and monitoring
        icon: prometheus.png
    - Grafana:
        href: https://home.brettswift.com/grafana
        description: Monitoring dashboards and visualization
        icon: grafana.png
