- resources:
    cpu: true
    memory: true
    disk:
    - /data

- kubernetes:
    server: https://kubernetes.default.svc
    token: ""
    skipTLSVerify: true
    namespace: homepage
    cluster:
      # Shows cluster-wide statistics
      show: true
      # Shows the aggregate CPU stats
      cpu: true
      # Shows the aggregate memory stats
      memory: true
      # Shows a custom label
      showLabel: true
      label: "cluster"
    nodes:
      # Shows node-specific statistics
      show: true
      # Shows the CPU for each node
      cpu: true
      # Shows the memory for each node
      memory: true
      # Shows the label, which is always the node name
      showLabel: true
