- resources:
    cpu: true
    memory: true
    disk:
    - /data

- kubernetes:
    cluster:
      # Shows cluster-wide statistics
      show: true
      # Shows the aggregate CPU stats
      cpu: true
      # Shows the aggregate memory stats
      memory: true
      # Shows a custom label
      showLabel: true
      label: "cluster"
    nodes:
      # Shows node-specific statistics
      show: true
      # Shows the CPU for each node
      cpu: true
      # Shows the memory for each node
      memory: true
      # Shows the label, which is always the node name
      showLabel: true

- argocd:
    url: http://argocd-server.argocd.svc.cluster.local/argocd
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJob21lcGFnZTphcGlLZXkiLCJuYmYiOjE3NjQ1NjU3OTIsImlhdCI6MTc2NDU2NTc5MiwianRpIjoiMWUwNDA3MjktYjYzOS00OGVkLTg4YmEtYTc2YTdhOTVjOTcwIn0.McBxRrYT4rth1CDKi-XqcUXIhW_DsS9kf83jHzxTUwY
    refreshInterval: 10000