resources:
- namespace.yaml
- prometheus-configmap.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- prometheus-serviceaccount.yaml
- prometheus-ingress.yaml
- grafana-configmap.yaml
- grafana-dashboard-configmap.yaml
- grafana-dashboard-config.yaml
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-ingress.yaml
- uptime-kuma/
