apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-hello-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Hello from $(ENV_NAME)</title></head>
    <body>
      <h1>Hello from $(ENV_NAME)</h1>
      <p>This is a sample hello world application deployed via ArgoCD!</p>
    </body>
    </html>

