# qBittorrent Ingress
# Uses rewrite-target to strip /qbittorrent prefix
# qBittorrent serves from root path
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  namespace: qbittorrent
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-redirect-from: "/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "/qbittorrent/"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter 'href="/' 'href="/qbittorrent/';
      sub_filter 'src="/' 'src="/qbittorrent/';
      sub_filter 'action="/' 'action="/qbittorrent/';
      sub_filter_once off;
      sub_filter_types text/html text/css text/javascript application/javascript;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - home.brettswift.com
    secretName: home-brettswift-com-tls
  rules:
  - host: home.brettswift.com
    http:
      paths:
      - path: /qbittorrent(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: qbittorrent
            port:
              number: 8080
