apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway.yaml
- argocd-vs.yaml
- homepage-vs.yaml
- tls-secret.yaml

secretGenerator:
- name: home-brettswift-com-tls
  files:
  - tls.crt=certificates/home.brettswift.com.crt
  - tls.key=certificates/home.brettswift.com.key
  type: kubernetes.io/tls
  namespace: istio-system