apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../production

patches:
  - path: patches/resource-limits.yaml
  - path: patches/cert-manager.yaml
  - path: patches/storage.yaml
  
  # Host patches for all ingresses
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.home.brettswift.com
    target:
      kind: Ingress
      
  # TLS patches for all ingresses
  - patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.home.brettswift.com
    target:
      kind: Ingress

commonLabels:
  environment: development