apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-healthcheck
  namespace: downloads
data:
  check-vpn.sh: |
    #!/bin/sh
    if wget -q --spider http://google.com; then
      if [ "$(curl -s https://ipinfo.io/country)" != "CA" ] && [ "$(curl -s https://ipinfo.io/country)" != "US" ]; then
        exit 1
      fi
      exit 0
    else
      exit 1
    fi 