apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Special Jellyseerr annotations
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Accept-Encoding "";
      sub_filter '"/api' '"/jellyseerr/api';
      sub_filter '"/login' '"/jellyseerr/login';
      sub_filter '"/images' '"/jellyseerr/images';
      sub_filter_once off;
spec:
  ingressClassName: nginx
  tls:
    - secretName: wildcard-tls
      hosts:
        - home.brettswift.com
  rules:
    - host: home.brettswift.com
      http:
        paths:
          - path: /jellyseerr(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: jellyseerr
                port:
                  number: 5055 