apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/config
  - ../../base/namespaces
  - ../../base/storage-classes
  - ../../apps/jellyfin
  - ../../apps/sonarr
  - ../../apps/radarr
  - ../../apps/prowlarr
  - ../../apps/bazarr
  - ../../apps/jellyseerr
  - ../../apps/qbittorrent
  - ../../apps/gluetun

configMapGenerator:
  - name: nas-config
    files:
      - values.yaml

vars:
  - name: HOSTNAME
    objref:
      kind: ConfigMap
      name: nas-config
      apiVersion: v1
    fieldref:
      fieldpath: data.network.hostname

patches:
  - path: patches/resource-limits.yaml