# Network Configuration
network:
  hostname: home.brettswift.com

# AWS Configuration
aws:
  region: us-east-1
  hostedZoneId: ${AWS_HOSTED_ZONE_ID}

# SSL Configuration
ssl:
  email: ${LETS_ENCRYPT_EMAIL}

# Common Settings
timezone: America/Edmonton
uid: "1000"
gid: "1000"

# Storage Configuration
storage:
  path: /mnt/data
  size: 3500Gi
  nodeName: k3s-node

# VPN Configuration
vpn:
  provider: ipvanish
  countries: "Canada,United States"
  proxy:
    port: 8888