apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ingressroute
  namespace: media-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.brettswift.com`) && PathPrefix(`/jellyfin`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
      middlewares:
        - name: jellyfin-stripprefix
          namespace: media-services
  tls:
    secretName: home-brettswift-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jellyfin-stripprefix
  namespace: media-services
spec:
  stripPrefix:
    prefixes:
      - /jellyfin
