resources:
- namespace.yaml
- common-configmap.yaml
- wireguard-configmap.yaml
- sonarr-deployment.yaml
- sonarr-ingress.yaml
- sabnzbd-deployment.yaml
- sabnzbd-ingress.yaml
- radarr-deployment.yaml
- radarr-ingress.yaml
- prowlarr-deployment.yaml
- prowlarr-ingress.yaml
- lidarr-deployment.yaml
- lidarr-ingress.yaml
- bazarr-deployment.yaml
- bazarr-ingress.yaml
- jellyseerr-deployment.yaml
- jellyseerr-ingress.yaml
