apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik-infrastructure
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: production
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-traefik-infrastructure'
      namespace: argocd
    spec:
      project: infrastructure
      source:
        repoURL: git@github.com:brettswift/k8s_nas.git
        targetRevision: main
        path: apps/infrastructure/traefik
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
