apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: homeautomation
  labels:
    app: matter-server
spec:
  selector:
    app: matter-server
  ports:
  - name: websocket
    port: 5580
    targetPort: 5580
  type: ClusterIP

