apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml
  - wildcard-certificate.yaml

configMapGenerator:
  - name: cert-config
    literals:
      - LETS_ENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - AWS_REGION=${AWS_REGION} 